######################################################################
# Automatically generated by qmake (3.0) Sat Jan 18 14:03:18 2014
######################################################################

TEMPLATE = app
TARGET = foreachRefCount
INCLUDEPATH += .
QT += core

# Input
SOURCES += qt_foreachRefCount.cpp
