/*
 * =====================================================================================
 *
 *       Filename:  compilerGeneratedFunctions.cpp
 *
 *    Description:  Example of compiler generated function
 *
 *        Version:  1.0
 *        Created:  27/09/13 09:31:36
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Damian Ziobro        (ziobro.damian@gmail.com)
 *        Company:  XMementoIT Limited       (info@xmementoit.com)
 *
 * =====================================================================================
 */

#include <iostream>

//I - when we are defining this class constructor will generate class as in
//point II. However only functions which we are using in our code will be generated.
class TestClass {

};


//II - body of class which will be generated by constructor
//class TestClass {
//public:
    //TestClass (){...}; //default constructor
    //~TestClass (){...}; //destructor
    //TestClass(const TestClass& inst){...}; //copy constructor
    //TestClass& operator=(const TestClass& inst){...}; //copy assignment operator
//};

int main(int argc, const char *argv[])
{
    TestClass instance; //III - we are using default constructor - it is generated by compiler 
    TestClass instance2(instance); // IV - we are using copy constructor - it si generated by compiler 
    TestClass instance3 = instance2; //V - we are using copy assignment operator - it is generated by compiler
        
    return 0; //VI - destructor is being invoking here - it is generated by compiler
}
